import { Entity, Column, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn, Index } from 'typeorm';

/**
 * Entity for storing extraction templates generated by AI
 * Templates contain CSS selectors and XPath for extracting content from news websites
 */
@Entity('extraction_templates')
@Index(['source', 'isActive']) // Composite index for common query: WHERE source = ? AND isActive = true
@Index(['source', 'version']) // Composite index for UNIQUE constraint
export class ExtractionTemplateEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ type: 'varchar', length: 100 })
  @Index() // Index for source lookups
  source!: string; // 'bloomberg', 'reuters', 'cointelegraph', etc.

  @Column({ type: 'int', default: 1 })
  version!: number; // Version of template (increment when regenerated)

  // CSS Selectors
  @Column({ type: 'text', nullable: true })
  titleSelector?: string; // CSS selector for title (e.g., 'h1, [data-module="Article"] h1')

  @Column({ type: 'text', nullable: true })
  summarySelector?: string; // CSS selector for summary

  @Column({ type: 'text', nullable: true })
  contentSelector?: string; // CSS selector for main content

  @Column({ type: 'text', nullable: true })
  publishTimeSelector?: string; // CSS selector for publish time

  // XPath fallbacks
  @Column({ type: 'text', nullable: true })
  xpathTitle?: string; // XPath for title (fallback)

  @Column({ type: 'text', nullable: true })
  xpathContent?: string; // XPath for content (fallback)

  // Template metadata
  @Column({ type: 'boolean', default: true })
  @Index() // Index for filtering active templates
  isActive!: boolean; // Whether this template is currently active

  @Column({ type: 'int', default: 0 })
  successCount!: number; // Number of successful extractions using this template

  @Column({ type: 'int', default: 0 })
  failCount!: number; // Number of failed extractions

  @Column({ type: 'timestamp', nullable: true })
  @Index() // Index for sorting by last used
  lastUsedAt?: Date; // Last time this template was used

  @Column({ type: 'timestamp', nullable: true })
  lastValidatedAt?: Date; // Last time template was validated

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;
}

